db:
  host: "postgres"
  user: "postgres"
  dbname: "bookstore"
  port: "5432"
  pass : "Adg12332,"

app:
  hash: "alenov"

payment:
  callbackurl: ""
  checkoutUrl: "https://pay.fondy.eu/api/checkout/url/"
  merchantId: "1396424"
  merchantPassword: "test"

redis:
  host: "redis:6379"
  password: ""
  db: 

mongoDB:
  host: "mongodb://mongoDb:27017"